# Generated by Django 5.1.7 on 2025-03-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='users.user'),
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='currentaddress',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_address', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='educationaldegree',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_degrees', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='candidates.candidate'),
        ),
    ]
