# Generated by Django 5.1.7 on 2025-03-24 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlightkey', models.TextField()),
                ('highlightvalue', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_highlights', to='candidates.candidate')),
            ],
            options={
                'db_table': 'TBL_CANDIDATE_HIGHLIGHTS',
            },
        ),
    ]
