# Generated by Django 5.1.7 on 2025-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidatehighlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='dp_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='video_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
