# Generated by Django 5.1.7 on 2025-03-24 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidate_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dp_id',
            field=models.TextField(blank=True, db_column='dp_id', null=True),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='dp_id',
            new_name='dpId',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience_summary',
            field=models.TextField(blank=True, db_column='experience_summary', null=True),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='experience_summary',
            new_name='experienceSummary',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='street_address',
            field=models.CharField(blank=True, db_column='street_address', max_length=255, null=True),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='street_address',
            new_name='streetAddress',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='technical_summary',
            field=models.TextField(blank=True, db_column='technical_summary', null=True),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='technical_summary',
            new_name='technicalSummary',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='video_id',
            field=models.TextField(blank=True, db_column='video_id', null=True),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='video_id',
            new_name='videoId',
        ),
        migrations.AlterField(
            model_name='candidatehighlights',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.RenameField(
            model_name='candidatehighlights',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='candidatehighlights',
            name='highlightkey',
            field=models.TextField(db_column='highlightkey'),
        ),
        migrations.RenameField(
            model_name='candidatehighlights',
            old_name='highlightkey',
            new_name='highlightKey',
        ),
        migrations.AlterField(
            model_name='candidatehighlights',
            name='highlightvalue',
            field=models.TextField(db_column='highlightvalue'),
        ),
        migrations.RenameField(
            model_name='candidatehighlights',
            old_name='highlightvalue',
            new_name='highlightValue',
        ),
        migrations.AlterField(
            model_name='candidatehighlights',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.RenameField(
            model_name='candidatehighlights',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.RenameField(
            model_name='candidateskill',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='skill_level',
            field=models.IntegerField(db_column='skill_level'),
        ),
        migrations.RenameField(
            model_name='candidateskill',
            old_name='skill_level',
            new_name='skillLevel',
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='skill_name',
            field=models.CharField(db_column='skill_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='candidateskill',
            old_name='skill_name',
            new_name='skillName',
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.RenameField(
            model_name='candidateskill',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AlterField(
            model_name='currentaddress',
            name='is_current_address',
            field=models.BooleanField(db_column='is_current_address', default=True),
        ),
        migrations.RenameField(
            model_name='currentaddress',
            old_name='is_current_address',
            new_name='isCurrentAddress',
        ),
        migrations.AlterField(
            model_name='currentaddress',
            name='street_address',
            field=models.CharField(db_column='street_address', max_length=255),
        ),
        migrations.RenameField(
            model_name='currentaddress',
            old_name='street_address',
            new_name='streetAddress',
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.RenameField(
            model_name='educationaldegree',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='field_of_study',
            field=models.CharField(db_column='field_of_study', max_length=200),
        ),
        migrations.RenameField(
            model_name='educationaldegree',
            old_name='field_of_study',
            new_name='fieldOfStudy',
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='graduation_date',
            field=models.DateField(db_column='graduation_date'),
        ),
        migrations.RenameField(
            model_name='educationaldegree',
            old_name='graduation_date',
            new_name='graduationDate',
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='graduation_month',
            field=models.CharField(db_column='graduation_month', max_length=20),
        ),
        migrations.RenameField(
            model_name='educationaldegree',
            old_name='graduation_month',
            new_name='graduationMonth',
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='graduation_year',
            field=models.IntegerField(db_column='graduation_year'),
        ),
        migrations.RenameField(
            model_name='educationaldegree',
            old_name='graduation_year',
            new_name='graduationYear',
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.RenameField(
            model_name='educationaldegree',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='current_job',
            field=models.BooleanField(db_column='current_job', default=False),
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='current_job',
            new_name='currentJob',
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, db_column='end_date', null=True),
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='candidate',
            name='lastName',
            field=models.CharField(blank=True, db_column='last_name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='companyName',
            field=models.CharField(blank=True, db_column='company_name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='contactNumber',
            field=models.CharField(blank=True, db_column='contact_number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='startDate',
            field=models.DateField(blank=True, db_column='start_date', null=True),
        ),
        migrations.AlterField(
            model_name='candidatehighlights',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateHighlights', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateSkills', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='currentaddress',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currentAddress', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationalDegrees', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialMediaLinks', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workExperiences', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
