# Generated by Django 4.2.5 on 2025-03-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_alter_candidate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatehighlights',
            name='highlightKey',
            field=models.TextField(blank=True, db_column='highlightkey', null=True),
        ),
        migrations.AlterField(
            model_name='candidatehighlights',
            name='highlightValue',
            field=models.TextField(blank=True, db_column='highlightvalue', null=True),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='skillLevel',
            field=models.IntegerField(blank=True, db_column='skill_level', null=True),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='skillName',
            field=models.CharField(blank=True, db_column='skill_name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentaddress',
            name='isCurrentAddress',
            field=models.BooleanField(blank=True, db_column='is_current_address', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentaddress',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='currentaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentaddress',
            name='streetAddress',
            field=models.CharField(blank=True, db_column='street_address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='fieldOfStudy',
            field=models.CharField(blank=True, db_column='field_of_study', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='graduationDate',
            field=models.DateField(blank=True, db_column='graduation_date', null=True),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='graduationMonth',
            field=models.CharField(blank=True, db_column='graduation_month', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='graduationYear',
            field=models.IntegerField(blank=True, db_column='graduation_year', null=True),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='currentJob',
            field=models.BooleanField(blank=True, db_column='current_job', default=False, null=True),
        ),
    ]
