# Generated by Django 5.1.7 on 2025-04-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_alter_candidatehighlights_highlightkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='professionInfo',
            field=models.TextField(blank=True, db_column='profession_info', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='streetAddress2',
            field=models.CharField(blank=True, db_column='street_address2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='zipCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastName',
            field=models.CharField(db_column='last_name', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
