# Generated by Django 5.1.7 on 2025-05-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_candidate_city_candidate_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='likes',
            field=models.IntegerField(db_column='likes', default=0),
        ),
    ]
